name: surgeWarp

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
jobs:
  run-script:
    runs_on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script
      run: |
        # 下载文件
        curl -o downloaded_file https://subs.zeabur.app/surge || echo "Failed to download file"

        # 提取 [Proxy] 和 [WireGuard] 字段
        awk 'BEGIN{RS=""; ORS="\n\n"} /^\[Proxy\]/ || /^\[WireGuard/' downloaded_file > extracted_content || echo "Failed to extract content"

        # 在提取的内容中删除包含 “[Proxy]” 的行
        sed -i '/\[Proxy\]/d' extracted_content || echo "Failed to delete [Proxy] lines"

        # 在提取的内容后追加一行，写入字符串：[Proxy Group]
        echo -e "\n[Proxy Group]" >> extracted_content || echo "Failed to append [Proxy Group]"

        # 检查 b.conf 文件是否存在
        if [ ! -f b.conf ]; then
          echo "b.conf does not exist"
        fi

        # 读取 b.conf 文件的内容，然后将其中的 [Proxy Group] 替换为步骤1修改后的内容
        sed '/\[Proxy Group\]/r extracted_content' b.conf | sed '/\[Proxy Group\]/d' > surgeWarp.conf || echo "Failed to create surgeWarp.conf"

        # 删除临时文件
        rm downloaded_file extracted_content || echo "Failed to delete temporary files"

        # 检查 surgeWarp.conf 文件是否存在
        if [ ! -f surgeWarp.conf ]; then
          echo "surgeWarp.conf does not exist"
        else
          echo "surgeWarp.conf was created successfully"
        fi
